name: iOS Build
  on:
    push:
      branches: [ 1.0 ]
  jobs:
    build-ios:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build iOS
        run: ./gradlew composeApp:embedAndSignAppleFrameworkForXcode 
